language: python

sudo: false

python:
  "3.8"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - python setup.py install

script:
  - echo

deploy:
  provider: pypi
  edge: true # opt in to dpl v2
  skip_existing: true
  on:
    tags: true
